version: '3.8'
services:
  java-server:
    build: ./java-server
    ports:
      - '8080:8080'
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./creds:/creds:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/creds/creds.json

  static-client:
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./client:/usr/share/nginx/html:ro
